### ISSUE TITLE
Periodic saving error

### ISSUE THREAD

**Issue by gasperkrivic** [ladisk/LDAQ#39]
Traceback (most recent call last):
  File "D:\dokturat\aktuator\aktuator_venv\lib\site-packages\LadiskDAQ\core.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "D:\dokturat\aktuator\aktuator_venv\lib\site-packages\LadiskDAQ\core.py", line 484, in _save_measurement_periodically
    file_index = self._open_and_save(file_name, root, file_index)
  File "D:\dokturat\aktuator\aktuator_venv\lib\site-packages\LadiskDAQ\core.py", line 550, in _open_and_save
    with open(file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'meritve\\20230531_111303_slia_2_10.pkl'
sys:1: ResourceWarning: Unclosed socket <zmq.Socket(zmq.PUSH) at 0x20dc51001c0>
ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by TKosir** [comment]
@gasperkrivic Do you remember what we discussed about this issue and have we already solved it? I cannot remember what went wrong here.

**Comment by gasperkrivic** [comment]
Periodic saving was working fine for about 10 measurements; however, I encountered an error and the visualization crashed randomly. Fortunately, I haven't encountered the same problem during my subsequent measurements.

**Comment by TKosir** [comment]
solved for now. Some minor details are in code TODO list
